[project]
name = "webots-projects"
version = "0.1.0"
description = "Webots worlds, controllers, and resources for my robotics university course"
readme = "README.md"
authors = [
    { name = "Alex Senger", email = "alex.senger@icloud.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "ikpy>=4.0.0",
    "matplotlib>=3.10.9",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
